### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by Kguo-cs** [yangchen1997/WcDT#1]
Interesting work. Could you please provide me the pretrained model?

**Comment by SHITIANYU-hue** [comment]
Yes sure, we will provide the pre-trained model soon.

**Comment by Kguo-cs** [comment]
There is no code for evaluating model and GENE_SUBMISSION. Could your please provide these code as well?

**Comment by yangchen1997** [comment]
We refactored our project before opening the source code, and for the new version of the code GENE_SUBMISSION related features are under development.
