### ISSUE TITLE
data access failed

### ISSUE THREAD

**Issue by Liupei-Luna** [yangchen1997/WcDT#2]
![image](https://github.com/yangchen1997/WcDT/assets/33121711/9eb68f9e-061d-4917-bdca-08e5c50fdd4b)

**Comment by yangchen1997** [comment]
![截图 2024-04-19 15-07-34](https://github.com/yangchen1997/WcDT/assets/55997638/2d28ff7f-898d-4611-bad9-fbc3479301e5)
如果是第一次下载waymo数据集，需要注册相关信息，步骤如下：
1、打开waymo的官网https://waymo.com/open/
2、选择”download“
3、填写相关信息
4、选择要下载的数据集（此项目使用的是motion preidction数据集）

**Comment by yangchen1997** [comment]
问题已解决
