### ISSUE TITLE
Pickle load file error.

### ISSUE THREAD

**Issue by dataminingvisit** [yangchen1997/WcDT#3]
"
import pickle as pk
with open(os.path.join(self.__dataset_dir, self.__pkl_list[idx]), "rb") as f:
        result = pickle.load(f)
"
Very sorry. I have one simple question: when I use this code to import "training.tfrecord-00000-of-01000", it would show "UnpicklingError: invalid load key, '~'." Do you know how to solve it? Thank you for your help.

**Comment by yangchen1997** [comment]
Thank you very much for your interest in this project. According to your description, your code throws an exception when loading training.tfrecord-00000-of-01000. For this issue, I think you need to run the "DATA_PREPROCESS" task first and then the "DATA_SPLIT" task. In this project, I have designed a pipeline where you need to execute all the tasks in the order of task_list in config.yaml, if there is a certain task which is not executed, then the later tasks will throw an error.
